version: '3'
services:
  db:
    image: postgres:13
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: nongki_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: ./main
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
